# Generated by Django 4.0.3 on 2022-04-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishgrammar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='getGram1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PoS', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField()),
            ],
        ),
    ]
